name: dependencies
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  cupertino_icons:
  flutter_native_splash:
  adaptive_theme:
  card_swiper:
  selectable:
  provider:
  path_provider:
  external_path:
  permission_handler:
  shared_preferences:
  sqflite:
  photo_view:
#   headset_connection_event:
  audioplayers:
  video_player:
  video_thumbnail:
  dio: ^4.0.6
  version: ^3.0.2
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  app_dev_config:
  dcdg:

flutter:
  uses-material-design: true

app_dev_config:
  android:
    apply: true
    compile_sdk: 33
    min_sdk: 21
    target_sdk: 29
