name: Build application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build_apk:
    name: Build APKs
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Get current date and time
        id: datetime
        run: echo "builddate=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Install Java
        uses: actions/setup-java@main
        with:
          distribution: "temurin"
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # - name: Build app (debug)
      #   run: flutter build apk --debug

      # - name: Build app (release)
      #   run: flutter build apk --release

      - name: Buscar paths (test)
        run: where flutter
        run: where java
        run: dir %homepath%
