name: Build application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build_apk:
    name: Build APKs
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-java@main
        with:
          distribution: "temurin"
          java-version: "11.x"

      - uses: subosito/flutter-action@main
        with:
          channel: "stable"
          
      - run: flutter --version
          
      - run: flutter doctor
          
      - run: flutter config

      - run: flutter pub get

      - run: dir C:\hostedtoolcache\windows
      
      - run: dir C:\Users\runneradmin

      # - name: Build app (debug)
      #   run: flutter build apk --debug

      # - name: Build app (release)
      #   run: flutter build apk --release
